kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: digitalgarden
  namespace: alyssa
  labels:
    app: digitalgarden
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "18"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'digitalgarden:latest'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      from:
        kind: ImageStreamTag
        name: fedora:39
        namespace: library
  triggers:
  - imageChange:
      from:
        kind: ImageStreamTag
        name: fedora:39
        namespace: library
