kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: digitalgarden-dev
  namespace: alyssa
  labels:
    app: digitalgarden
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "18"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'digitalgarden:latest'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      from:
        kind: ImageStreamTag
        name: fedora:39
        namespace: library
  source:
    type: Git
    git:
      uri: 'https://github.com/its-a-lisa/digitalgarden-site'
    triggers:
      - type: Generic
        generic:
          secretReference:
            name: digitalgarden-github
      - type: ImageChange
        imageChange:
          from:
            kind: ImageStreamTag
            namespace: alyssa
            name: 'fedora:39'
      - type: ConfigChange
    runPolicy: Serial