kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: digitalgarden
  namespace: alyssa
  labels:
    app: digitalgarden
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "18"
spec:
  lookupPolicy:
    local: false